### ISSUE TITLE
Publish the latest alpha?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [micnic/simples#12]
Any chance you could publish the latest alpha on the npm registry?

You can use the `--tag [name]` option with `npm publish` so that `npm install simples` continues to install version `0.8.8` (the default dist-tag is `latest`) while `npm install simples@[name]` will install the tagged version. For alpha pre-releases it's common to use `next` or `alpha` for the dist-tag, e.g. `npm publish --tag next`, `npm install simples@next`.

And/or could you include a `prepare` script (that does the needed build step/s) in `package.json` so the package can be installed (with npm) directly from GitHub?

That would allow a user to spec simples as `"simples": "micnic/simples"` in dev/dependencies of the user's `package.json`, so that it installs directly from the `master` branch on GitHub with a transparent build step.

**Comment by micnic** [comment]
Updated github & npm with the latest alpha version
